### ISSUE TITLE
when the code for vision release? 

### ISSUE THREAD

**Issue by bok3948** [Skhaki18/optin-transformer-pruning#2]
Hi thanks for great jobs. 

I'm want to use your code for my research(to get baseline)  
when the code for vision release?  

thanks.

**Comment by Skhaki18** [comment]
Thank you for your interest in our project. The vision code has been released, along with pre-computed parameter rankings.

**Comment by mariam-jamal** [comment]
Hi,
Firstly, thank you for the amazing work. 
I was trying to reproduce the code, but I see in the configs, only deit-small-patch is there.. do you plan to also release configs for other vision models, for eg: vit-base-patch16-224?
Also, is there a tutorial on how to use the method for other use cases for eg, audio?

**Comment by Skhaki18** [comment]
Thank you for your interest in our project. I plan to release the additional vision configurations by the end of next week. At this time, we don't have a tutorial for adding audio use cases, however, we do imagine that this pipeline is transferable. To add a new use case, you may simply follow the existing structure for vision use cases. In particular, adding a config.yaml, a data_class file in "/data/scripts", corresponding evaluation code in "evals" and modifying the main_prune.py `elif args.task_name == "vision":` to `elif args.task_name in ["vision", "audio"]:` as the same vision pruning scripts will likely work for the audio classification use case. I will add a section to the README.md with more concrete instructions on how to extend to alternate use cases in the upcoming week.
